services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teammanager
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - teammanager-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    networks:
      - teammanager-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev:local"

networks:
  teammanager-network:
    driver: bridge

volumes:
  postgres-data:
